//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DT_POC_NotFound
    {
        public int ID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string File_Selected_By_User { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> Received_TimeStamp { get; set; }
        public Nullable<System.DateTime> Processed_TimeStamp { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> Institute_ID { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public byte[] Attachment { get; set; }
    }
}
