//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DT_PatientReferralMRN
    {
        public int ID { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Institute_ID { get; set; }
        public string InstitutePatientMRN { get; set; }
    }
}
