//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DT_Incoming_Message_Individual_Attachments
    {
        public int ID { get; set; }
        public Nullable<int> InComingMessageID { get; set; }
        public string FileName { get; set; }
        public string FileData { get; set; }
        public Nullable<int> ReferralProcessedID { get; set; }
    }
}
