//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppError
    {
        public short Erowid { get; set; }
        public string Module { get; set; }
        public string ErrorMessage { get; set; }
        public string NPINumber { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdts { get; set; }
    }
}
