//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClinics()
        {
            this.tblPatients = new HashSet<tblPatients>();
        }
    
        public short Crowid { get; set; }
        public string ClinicNo { get; set; }
        public string ClinicName { get; set; }
        public string FriendlyName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string NPINumber { get; set; }
        public string TaxId { get; set; }
        public string SchStartTime { get; set; }
        public string SchEndTime { get; set; }
        public string SchFrequency { get; set; }
        public byte ApptNumber { get; set; }
        public string TherapistId { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdts { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedts { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<short> BillingOfficeNo { get; set; }
        public string Folder { get; set; }
        public string BC2GroupId { get; set; }
        public string DptLabNum { get; set; }
        public Nullable<bool> billing { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public string MarketingClinicName { get; set; }
        public string PhyStreetAddress { get; set; }
        public string PhyCity { get; set; }
        public string PhyState { get; set; }
        public string PhyZipcode { get; set; }
        public string CustId { get; set; }
        public string SMSKey { get; set; }
        public Nullable<bool> SMSToBeSent { get; set; }
        public string SMSText { get; set; }
        public string SMSpwd { get; set; }
        public string FromNumber { get; set; }
        public byte[] LogoFile { get; set; }
        public Nullable<bool> UseLogo { get; set; }
        public Nullable<bool> POPT { get; set; }
        public Nullable<short> ClinicType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatients> tblPatients { get; set; }
    }
}
