//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDevice
    {
        public int Drowid { get; set; }
        public string PhoneNumber { get; set; }
        public string DeviceId { get; set; }
        public string EmailId { get; set; }
        public string SignPath { get; set; }
        public string OTP { get; set; }
    }
}
