//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDocMaster()
        {
            this.tblAppNotifications = new HashSet<tblAppNotification>();
        }
    
        public int Docrowid { get; set; }
        public Nullable<int> PTrowid { get; set; }
        public string NoteType { get; set; }
        public short TreatingTherapistId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DateOfService { get; set; }
        public bool Signed { get; set; }
        public System.DateTime SignedDate { get; set; }
        public string PDFName { get; set; }
        public short AuthorizedBy { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdts { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedts { get; set; }
        public Nullable<int> BMrowid { get; set; }
        public string CPCrtd { get; set; }
        public string ReBillInd { get; set; }
        public string DDCrtd { get; set; }
        public Nullable<bool> reportFlag { get; set; }
        public Nullable<short> markedaserror { get; set; }
        public string FRComp { get; set; }
        public string ThType { get; set; }
        public string PDFName2 { get; set; }
        public string PDFName3 { get; set; }
        public string ReferralSource2 { get; set; }
        public string ReferralSource3 { get; set; }
        public string ReferralSource { get; set; }
        public string InsuranceNo { get; set; }
        public string BillAsFirstName { get; set; }
        public string BillAsLastName { get; set; }
        public string Resubmission { get; set; }
        public string OriRefNo { get; set; }
        public string AddlClaimInfo { get; set; }
        public string Note { get; set; }
        public Nullable<short> homevisit { get; set; }
        public string keymodule { get; set; }
        public string keyexponent { get; set; }
        public string DigitalSignature { get; set; }
        public string HashBit { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public string keymodule2 { get; set; }
        public string keyexponent2 { get; set; }
        public string DigitalSignature2 { get; set; }
        public string HashBit2 { get; set; }
        public Nullable<System.DateTime> SignatureDate2 { get; set; }
        public string keymodule3 { get; set; }
        public string keyexponent3 { get; set; }
        public string DigitalSignature3 { get; set; }
        public string HashBit3 { get; set; }
        public Nullable<System.DateTime> SignatureDate3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppNotification> tblAppNotifications { get; set; }
    }
}
