//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirectTrustPatientLog
    {
        public int DPTLogid { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string Messageid { get; set; }
        public string Operation { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string Sender { get; set; }
    }
}
