//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPatients()
        {
            this.tblAppNotifications = new HashSet<tblAppNotification>();
            this.tblAppNotifications1 = new HashSet<tblAppNotification>();
        }
    
        public int Prowid { get; set; }
        public short ClinicNo { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string MiddleInitial { get; set; }
        public string Gender { get; set; }
        public string BirthDate { get; set; }
        public string ReferralDate { get; set; }
        public string InjuryDate { get; set; }
        public string DischargeDate { get; set; }
        public string ReferralSource { get; set; }
        public Nullable<bool> PostOp { get; set; }
        public string Note { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string HomePh { get; set; }
        public bool HomePhO { get; set; }
        public bool HomePhB { get; set; }
        public string WorkPh { get; set; }
        public bool WorkPhO { get; set; }
        public bool WorkPhB { get; set; }
        public string CellPh { get; set; }
        public bool CellPhO { get; set; }
        public bool CellPhB { get; set; }
        public string OtherPh { get; set; }
        public bool OtherPhO { get; set; }
        public bool OtherPhB { get; set; }
        public string Email { get; set; }
        public bool NoEmail { get; set; }
        public bool NoMarketingEmail { get; set; }
        public Nullable<int> TherapistID { get; set; }
        public string firstvisitdate { get; set; }
        public Nullable<bool> RenumberPatientID { get; set; }
        public string Race { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdts { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedts { get; set; }
        public string Discipline { get; set; }
        public Nullable<bool> CapMet { get; set; }
        public Nullable<bool> OTCapMet { get; set; }
        public string ReferralSource2 { get; set; }
        public string ReferralSource3 { get; set; }
        public Nullable<bool> ApptRemind { get; set; }
        public Nullable<bool> ApptRemindEval { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DPTrowid { get; set; }
        public Nullable<bool> DTTrustFlg { get; set; }
        public Nullable<bool> BundlePatient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppNotification> tblAppNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppNotification> tblAppNotifications1 { get; set; }
        public virtual tblClinics tblClinics { get; set; }
    }
}
