//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatScannedDocs
    {
        public int SFrowid { get; set; }
        public Nullable<int> PTrowid { get; set; }
        public string PDFName { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdts { get; set; }
        public string doctype { get; set; }
    }
}
