//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferrer
    {
        public int Rrowid { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PrintName { get; set; }
        public string NPINumber { get; set; }
        public string Email { get; set; }
        public string ReferralType { get; set; }
        public string SendPOCBy { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdts { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedts { get; set; }
        public string Credentials { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public string AltContInfo { get; set; }
        public Nullable<bool> NoFax { get; set; }
        public Nullable<int> ReferralInstitute { get; set; }
    }
}
