//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchedules
    {
        public int Srowid { get; set; }
        public short ClinicId { get; set; }
        public short TherapistId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string StartDateTime { get; set; }
        public string EndDateTime { get; set; }
        public string Description { get; set; }
        public short CanCode { get; set; }
        public Nullable<short> ApptCode { get; set; }
        public string ApptType { get; set; }
        public string CheckedIn { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdts { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedts { get; set; }
        public string CoPay { get; set; }
        public string Transport { get; set; }
    }
}
