//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTherapist
    {
        public short TherapistID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FriendlyName { get; set; }
        public short DefaultClinic { get; set; }
        public string Credentials { get; set; }
        public string LicenseNumber { get; set; }
        public byte[] SignatureFile { get; set; }
        public bool Floater { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string BillAs { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdts { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedts { get; set; }
        public string NPINumber { get; set; }
        public string TherapistType { get; set; }
        public Nullable<short> HomeVisit { get; set; }
    }
}
