//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team.Rehab.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public short Urowid { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserPassword { get; set; }
        public short UserGroup { get; set; }
        public bool UserActive { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdts { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedts { get; set; }
        public string UserEmail { get; set; }
        public Nullable<short> DefaultClinic { get; set; }
        public Nullable<System.Guid> UserGuid { get; set; }
    }
}
